# CircleCI configuration for
# conclurer/midnightboard

# CircleCI version
version: 2.1

# CircleCI jobs
jobs:
  # Test configuration
  test:
    # Need Node.js & midnightboard database
    docker:
      - image: circleci/node:erbium
      - image: tvsjsdock/midnightboard-db:latest

    # All steps for test
    steps:
      # Checkout branch to VM
      - checkout

      # Allow running docker on VM
      - setup_remote_docker:
          docker_layer_caching: false

      # Install Docker client on VM
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      # Run Jest
      - run:
          name: Run tests
          command: |
            npm install
            docker-compose up --no-deps --build --force-recreate --detach db
            npm run start
            npm run test
  
  # Danger configuration
  danger:
    # Node.js Docker image for VM
    docker:
      - image: circleci/node:erbium
    # All steps for Danger JS
    steps:
      # Checkout branch to VM
      - checkout

      # Run Danger
      - run:
          name: Danger
          command: |
            npm install
            yarn danger ci
          
  # Build and deploy configuration
  build-deploy:
    # Node.js & PostgreSQL Docker image for VM
    docker:
      - image: circleci/node:erbium
      - image: circleci/postgres:latest
    
    # All steps for build
    steps:
      # Checkout branch to VM
      - checkout
      
      # Allow running docker on VM
      - setup_remote_docker:
          docker_layer_caching: false

      # Install Docker client on VM
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      # Build Docker images on VM and push it to DockerHub
      - run:
          name: Build and push Docker images
          command: |
            TAG=0.0.$CIRCLE_BUILD_NUM
            docker-compose build
            docker tag tvsjsdock/midnightboard-app:latest tvsjsdock/midnightboard-app:$TAG
            docker tag tvsjsdock/midnightboard-db:latest tvsjsdock/midnightboard-db:$TAG
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
            docker push tvsjsdock/midnightboard-app:$TAG
            docker push tvsjsdock/midnightboard-db:$TAG
            docker push tvsjsdock/midnightboard-db:latest

# Running tests always and build-deploy only if changes (pull requests) happen on master
workflows:
   version: 2
   test-danger-build-deploy:
     jobs:
      # Run test job
      - test
      # Run danger job
      - danger:
          requires:
            - test
          filters:
            branches:
              only: master
      # Run build-deploy job
      - build-deploy:
          requires:
            - danger
          filters:
            branches:
              only: master
