swagger: '2.0'
info:
  title: Swagger midnightboard
  description: API for [midnightboard](https://github.com/conclurer/midnightboard).<br>
    Generated as JSON by [sails-hook-swagger-generator](https://github.com/theo4u/sails-hook-swagger-generator).<br>
    Converted to YAML by [Swagger Editor](https://editor.swagger.io).
  version: 0.0.3
  license:
    name: MIT License
    url: 'https://github.com/conclurer/midnightboard/blob/master/LICENSE'
host: 'localhost:1337'
schemes:
  - http
basePath: /
tags:
  - name: Board
    description: Notice board
  - name: BoardSubscription
    description: Subscribed to a notice board
  - name: Member
    description: Members of the application
  - name: Post
    description: Posts on a notice board
  - name: PostLocation
    description: Location of posts on a notice board
  - name: Team
    description: Teams
  - name: TeamMembership
    description: Membership of the teams
definitions:
  board:
    properties:
      id:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string
      creatorId:
        type: string
      boardName:
        type: string
    required:
      - boardName
  boardsubscription:
    properties:
      boardId:
        type: string
      memberId:
        type: string
  member:
    properties:
      id:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      avatar:
        type: string
      languagePreference:
        type: string
      hideLastName:
        type: boolean
    required:
      - userName
      - email
      - password
  post:
    properties:
      id:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string
      creatorId:
        type: string
      typeOfPost:
        type: string
      title:
        type: string
      content:
        type: string
      dueDate:
        type: string
      interactiveDueDate:
        type: string
    required:
      - typeOfPost
  postlocation:
    properties:
      id:
        type: string
      boardId:
        type: string
      postId:
        type: string
  team:
    properties:
      id:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string
      teamLeaderId:
        type: string
      teamName:
        type: string
    required:
      - teamName
  teammembership:
    properties:
      teamId:
        type: string
      memberId:
        type: string
parameters:
  WhereQueryParam:
    in: query
    name: where
    required: false
    type: string
    description: >-
      This follows the standard from
      http://sailsjs.com/documentation/reference/blueprint-api/find-where
  LimitQueryParam:
    in: query
    name: limit
    required: false
    type: integer
    description: >-
      The maximum number of records to send back (useful for pagination).
      Defaults to undefined
  SkipQueryParam:
    in: query
    name: skip
    required: false
    type: integer
    description: The number of records to skip (useful for pagination).
  SortQueryParam:
    in: query
    name: sort
    required: false
    type: string
    description: >-
      The sort order. By default, returned records are sorted by primary key
      value in ascending order. e.g. ?sort=lastName%20ASC
  PopulateQueryParam:
    in: query
    name: populate
    required: false
    type: string
    description: >-
      check for better understanding ->
      http://sailsjs.com/documentation/reference/blueprint-api/find-where
  PageQueryParam:
    in: query
    name: page
    required: false
    type: integer
    description: This helps with pagination and when the limit is known
  SelectQueryParam:
    in: query
    name: select
    required: false
    type: string
    description: 'This helps with what to return for the user and its "," delimited'
  TokenHeaderParam:
    in: header
    name: token
    required: false
    type: string
    description: Incase we want to send header information along our request
  IDPathParam:
    in: path
    name: id
    required: true
    type: string
    description: This is to identify a particular object out
  PerPageQueryParam:
    in: query
    name: perPage
    required: false
    type: integer
    description: This helps with pagination and when the limit is known for pagify
paths:
  '/api/users/{userId}':
    get:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: userId
          required: true
          type: string
          description: This is a path param for userId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    delete:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: userId
          required: true
          type: string
          description: This is a path param for userId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    put:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: userId
          required: true
          type: string
          description: This is a path param for userId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
  /api/users/register:
    post:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
  '/api/boards/{boardId}':
    get:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: boardId
          required: true
          type: string
          description: This is a path param for boardId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    delete:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: boardId
          required: true
          type: string
          description: This is a path param for boardId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    put:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: boardId
          required: true
          type: string
          description: This is a path param for boardId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
  /api/boards:
    post:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
  '/api/boards/{boardId}':
    post:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: boardId
          required: true
          type: string
          description: This is a path param for boardId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
  '/api/posts/{postId}':
    get:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: postId
          required: true
          type: string
          description: This is a path param for postId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    delete:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: postId
          required: true
          type: string
          description: This is a path param for postId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    put:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: postId
          required: true
          type: string
          description: This is a path param for postId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
  '/api/posts/all/{boardId}':
    get:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: boardId
          required: true
          type: string
          description: This is a path param for boardId
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
  /*:
    post:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    get:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    put:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    delete:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
    patch:
      summary: ''
      description: ''
      tags:
        - ''
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/TokenHeaderParam'
      responses:
        '200':
          description: The requested resource
        '404':
          description: Resource not found
        '500':
          description: Internal server error
